#!/bin/bash

build_and_install() {
  local version="$1"
   docker pull "octoblu/octoalpine:latest" \
   && docker pull "octoblu/octoalpine-docker:$version" \
   && uninstall "$version" \
   && build "$version" \
   && install "$version"
}

build() {
  local version="$1"
  docker build -t "local/octoswarm-$version" -f "./Dockerfile-$version" .
}

install() {
  local version="$1"
  whalebrew install "local/octoswarm-$version"
}

uninstall() {
  local version="$1"
  whalebrew uninstall "octoswarm-$version" 2> /dev/null || return 0
}

main() {
  build_and_install "1.13.1"
  build_and_install "17.03.0-ce"
}

main "$@"
