#!/bin/bash

fatal() {
  local message="$1"
  echo "Error: $message"
  exit 1
}

link_bin() {
  ln -nsf $(script_directory)/bin/* ~/.bin
}

rm_old_bin() {
  if [ -f "$HOME/.bin/swarm-start-service" ]; then
    rm ~/.bin/swarm-start-service
  fi
  if [ -f "$HOME/.bin/swarm-stop-service" ]; then
    rm ~/.bin/swarm-stop-service
  fi
  if [ -f "$HOME/.bin/swarm-restart-service" ]; then
    rm ~/.bin/swarm-restart-service
  fi
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

usage(){
  echo 'USAGE: install.sh'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help         print this help text'
  echo '  -v, --version      print the version'
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown"
  fi
}

main() {
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  link_bin
  rm_old_bin
  echo "INSTALLED!"
}

main "$@"
