#!/bin/bash

SCRIPT_NAME='stack-ensure-dns'

# shellcheck disable=SC1091
source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

usage(){
  echo "USAGE: ${SCRIPT_NAME} [OPTIONS] [/path/to/cluster.json]"
  echo ''
  echo 'Description: will setup A & SRV records.'
  echo ''
  echo "Example: ${SCRIPT_NAME}"
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo "  -n, --dry-run    show what records will be created/updated"
  echo "                   but don't actually do anything"
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}
# Script Functions

get_service_name() {
  local service="$1"
  echo "$service" | jq -r '.name'
}

# Primary execution

main() {
  while [ "$1" != "" ]; do
    local param="$1"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      -n | --dry-run)
        warn "Using '--dry-run'"
        export DRY_RUN='true'
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  is_stack_empty || fatal 'Not initialized, run `create-cluster`'

  get_config_array '.services[]' | while read -r service; do
    local name
    name="$(get_service_name "$service")"
    stack ensure-service-dns "$name" || fatal "unable to ensure service $name"
  done
}

main "$@"
