#!/bin/bash

SCRIPT_NAME="stack-create-machine"

# shellcheck disable=SC1091
source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

assert_required_params(){
  local machine_id="$1"
  local hub_username="$2"
  local hub_password="$3"

  if [ -n "$machine_id" ] && [ -n "$hub_username" ] && [ -n "$hub_password" ]; then
    return 0
  fi

  usage

  if [ -z "$machine_id" ]; then
    echo "machine_id is missing"
  fi

  if [ -z "$hub_username" ]; then
    echo "hub_username is missing"
  fi

  if [ -z "$hub_password" ]; then
    echo "hub_password is missing"
  fi
  exit 1
}

select_random_zone(){
  local zones=('a' 'b' 'c')
  local rand=$[$RANDOM % 3]
  echo "${zones[$rand]/,/}"
}

create_machine() {
  local machine_id="$1"
  shift
  local options="$@"
  echo "$(run_cmd docker-machine create $options "$machine_id")"
}

docker_login() {
  local machine_id="$1"
  local hub_username="$2"
  local hub_password="$3"
  shift; shift; shift
  local options="$@"
  run_cmd docker $(docker-machine config $options "$machine_id") login --username "$hub_username" --password "$hub_password"
}

usage(){
  echo "USAGE: $SCRIPT_NAME"
  echo ''
  echo 'Arguments:'
  echo '  -h, --help               print this help text'
  echo '  -t, --ec2-instance-type  ec2 instance type to spin up'
  echo '                           (default: t2.medium)'
  echo '  --docker-version         docker version to install'
  echo '                           (default: latest)'
  echo '  --ec2-tags               ec2 tags (comma delimited)'
  echo '  -v, --version            print the version'
  echo 'Environment:'
  echo '  DEBUG                    print debug output'
}

main() {
  local machine_id
  local ec2_instance_type="t2.medium"
  local docker_version
  local ec2_tags

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -t | --ec2-instance-type)
        ec2_instance_type="$value"
        shift
        ;;
      --ec2-tags)
        ec2_tags="$value"
        shift
        ;;
      --docker-version)
        docker_version="$value"
        shift
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$machine_id" ]; then
          machine_id="${param}"
        fi
        ;;
    esac
    shift
  done

  local hub_username="$DOCKER_HUB_USERNAME"
  local hub_password="$DOCKER_HUB_PASSWORD"
  local ec2_zone

  assert_required_params "$machine_id" "$hub_username" "$hub_password"

  debug "machine id $machine_id"

  ec2_zone="$(select_random_zone)"
  debug "using ec2 zone $ec2_zone"
  debug "using ec2 instance type $ec2_instance_type"

  echo "Creating $machine_id"

  local opt_engine_install_url
  if [ "$docker_version" == "1.12.6" ]; then
    opt_engine_install_url='--engine-install-url "https://packages.docker.com/1.12/install.sh"'
  elif [ "$docker_version" == "1.13.1" ]; then
    opt_engine_install_url='--engine-install-url "https://packages.docker.com/1.13/install.sh"'
  elif [[ "$docker_version" =~ ^17\.05\.0 ]]; then
    opt_engine_install_url='--engine-install-url "https://releases.rancher.com/install-docker/17.05.sh"'
  else
    echo "WARNING: docker-machine will use the latest version of docker"
  fi

  local opt_amazonec2_tags
  if [ "$ec2_tags" != "" ]; then
    opt_amazonec2_tags="--amazonec2-tags $ec2_tags"
  fi

  create_machine "$machine_id" \
    $opt_engine_install_url \
    --driver amazonec2 \
    $opt_amazonec2_tags \
    --amazonec2-access-key "$AWS_ACCESS_KEY_ID" \
    --amazonec2-secret-key "$AWS_SECRET_ACCESS_KEY" \
    --amazonec2-region "us-west-2" \
    --amazonec2-zone "$ec2_zone"\
    --amazonec2-root-size "50" \
    --amazonec2-instance-type "$ec2_instance_type" \
    --amazonec2-security-group "swarm-prod" \
    --amazonec2-security-group "swarm-prod-ssh" || fatal 'unable to create machine'
  debug 'sleep for 10 seconds to wait for docker'
  sleep 10
  docker_login "$machine_id" "$hub_username" "$hub_password"
  docker-machine ssh "$machine_id" sudo apt-get install -y ntp ntpstat
  sleep 2
  debug 'sleep for 60 seconds to wait for machine to reboot'
  docker-machine restart "$machine_id"
  sleep 60
}

main "$@"
