#!/bin/bash

SCRIPT_NAME="stack-ensure-services"

# shellcheck disable=SC1091
source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

usage(){
  echo "USAGE: $SCRIPT_NAME"
  echo 'Description: ensure all services are up-to-date'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help        print this help text'
  echo '  -v, --version     print the version'
  echo 'Environment:'
  echo '  DEBUG             print debug output'
}

assert_required_config() {
  require_config_value '.'
  require_config_value '.services[]'
}

get_service_name() {
  local service="$1"
  echo "$service" | jq -r '.name'
}

main() {
  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"

    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  assert_required_config

  # shellcheck disable=SC2016
  is_stack_empty || fatal 'Not initialized, run `create-cluster`'
  get_config_array '.services[]' | while read -r service; do
    local name
    name="$(get_service_name "$service")"
    stack ensure-service "$name" || fatal "unable to ensure service $name"
  done
}

main "$@"
