#!/bin/bash

source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

debug() {
  debug_core "stack-login" "$@"
}

usage(){
  echo 'USAGE: stack login'
  echo ''
  echo 'Description: Docker login that works'
  echo 'Arguments:'
  echo '  -h, --help         print this help text'
  echo '  -v, --version      print the version'
  echo ''
}

main() {
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' -a "$param" != "--" ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done
  for machine_id in $(get_machine_names); do
    debug 'machine_id' $machine_id
    docker-machine ssh "$machine_id" \
      "sudo docker --config /root/.docker/ login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD"
  done
}

main "$@"
