#!/bin/bash

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

source "$(script_directory)/utils" || fatal 'unable to load utils'

debug() {
  debug_core "stack-create-service" "$@"
}

assert_required_params(){
  local service_name="$1"
  local subdomain="$2"

  if [[ "$subdomain" =~ /octoblu\.com$/ ]]; then
    fatal "$subdomain cannot contain octoblu.com"
  fi

  if [ -n "$service_name" -a -n "$subdomain" ]; then
    return 0
  fi

  usage

  if [ -z "$service_name" ]; then
    echo "<service-name> is missing"
  fi

  if [ -z "$subdomain" ]; then
    echo "<subdomain> is missing"
  fi

  exit 1
}

assert_required_env() {
  if [ -n "$SWARM_ENV_DIR" ]; then
    return 0
  fi

  if [ -z "$SWARM_ENV_DIR" ]; then
    echo "Missing env SWARM_ENV_DIR."
  fi

  exit 1
}

generate_service(){
  local service_name="$1"
  local subdomain="$2"
  mkdir -p "$SWARM_ENV_DIR/services/$service_name"
  export SERVICE_NAME="$service_name" SUBDOMAIN="$subdomain"
  local start_script="$SWARM_ENV_DIR/services/$service_name/start"
  local stop_script="$SWARM_ENV_DIR/services/$service_name/stop"
  cat "$SWARM_ENV_DIR/services/_template/start" | envsubst > "$start_script" && chmod +x "$start_script"
  cat "$SWARM_ENV_DIR/services/_template/stop" | envsubst > "$stop_script" && chmod +x "$stop_script"
  unset SERVICE_NAME
  unset SUBDOMAIN
}

add_env() {
  local service_name="$1"
  echo "Have you added your env files to the correct stack?"
  say_yes || exit 1
}

usage(){
  echo 'USAGE: stack-create-service <service-name> <subdomain>'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help         print this help text'
  echo '  -v, --version      print the version'
  echo 'Environment:'
  echo '  DEBUG              print debug output'
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown"
  fi
}

main() {
  local service_name
  local subdomain

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$service_name" ]; then
          service_name="${param}"
        elif [ -z "$subdomain" ]; then
          subdomain="${param}"
        fi
        ;;
    esac
    shift
  done

  assert_required_env
  assert_required_params "$service_name" "$subdomain"
  add_env "$service_name"
  generate_service "$service_name" "$subdomain"
  echo "$service_name has been created"
}

main "$@"
