#!/bin/bash

SCRIPT_NAME='stack-auto-configure-dns'

# Utilities

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

assert_required_params() {
  local domain="$1"
  local zone_name="$2"

  if [ -n "$domain" ] && [ -n "$zone_name" ] && [ "$domain" != "null" ] && [ "$zone_name" != "null" ]; then
    return 0
  fi

  usage

  if [ -z "$domain" ] || [ "$domain" == "null" ]; then
    echo "Missing .domain property in the cluster.json"
  fi

  if [ -z "$zone_name"  ] || [ "$zone_name" == "null" ]; then
    echo "Missing .zoneName property in the cluster.json"
  fi

  exit 1
}

usage(){
  echo "USAGE: ${SCRIPT_NAME} [OPTIONS] [/path/to/cluster.json]"
  echo ''
  echo 'Description: will setup A & SRV records.'
  echo ''
  echo "Example: ${SCRIPT_NAME}"
  echo ''
  echo 'Arguments:'
  echo '  -h, --help       print this help text'
  echo "  -n, --dry-run    show what records will be created/updated"
  echo "                   but don't actually do anything"
  echo '  -v, --version    print the version'
  echo ''
  echo 'Environment:'
  echo '  DEBUG            print debug output'
  echo ''
}
# Script Functions

find_services(){
  jq '.services[].name' \
    --raw-output \
    "$config_path"
}

generate_change_batch(){
  local config_path="$1"
  local domain="$2"
  local load_balancer_dns="$3"
  local load_balancer_target_zone="$4"

  env \
    CONFIG_PATH="$config_path" \
    DOMAIN="$domain" \
    LOAD_BALANCER_DNS="$load_balancer_dns" \
    ZONE_ID="$load_balancer_target_zone" \
    stack write-route-53-multi-batch-file
}

get_domain() {
  local config_path="$1"
  jq --raw-output '.domain' "$config_path"
}

get_load_balancer_dns() {
  local load_balancer_name="$1"
  local load_balancers=( $(get_load_balancers "$load_balancer_name") )
  for load_balancer in "${load_balancers[@]}"; do
    local load_balancer_dns
    load_balancer_dns="$(echo "$load_balancer" | jq -r '.CanonicalHostedZoneName')"
    if [ -n "$load_balancer_dns" ]; then
      echo "$load_balancer_dns"
      return 0
    fi
  done
  return 1
}

get_load_balancer_name(){
  local config_path="$1"
  local elb_count

  elb_count="$(jq '.managers.elbs | length' "$config_path")"
  if [ "$elb_count" != "1" ]; then
    echo "Found multiple elbs, cowardly refusing to do anything: "
    echo "$(jq '.managers.elbs' "$config_path")"
    exit 1
  fi

  jq '.managers.elbs[]' \
    --raw-output \
    "$config_path"
}

get_load_balancer_target_zone() {
  local load_balancer_name="$1"
  local load_balancers=( $(get_load_balancers "$load_balancer_name") )
  for load_balancer in "${load_balancers[@]}"; do
    local load_balancer_target_zone
    load_balancer_target_zone="$(echo "$load_balancer" | jq -r '.CanonicalHostedZoneNameID')"
    if [ -n "$load_balancer_target_zone" ]; then
      echo "$load_balancer_target_zone"
      return 0
    fi
  done
  return 1
}

get_load_balancers() {
  local filter="$1"
  aws elb describe-load-balancers --load-balancer-names "$filter" | jq --compact-output  '.LoadBalancerDescriptions[]'
}

get_route53_hosted_zone(){
  local domain="$1"

  aws route53 list-hosted-zones \
  | jq --raw-output ".HostedZones | map(select(.Name == \"$domain\"))[0].Id"
}

get_zone_name() {
  local config_path="$1"
  jq --raw-output '.zoneName' "$config_path"
}

# Primary execution

main() {
  local change_batch
  local config_path
  local domain
  local dry_run='false'
  local load_balancer_dns
  local load_balancer_name
  local load_balancer_target_zone
  local route53_hosted_zone
  local tmpfile
  local zone_name

  while [ "$1" != "" ]; do
    local param="$1"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      -n | --dry-run)
        dry_run='true'
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$config_path" ]; then
          config_path="$param"
        fi
        ;;
    esac
    shift
  done

  if [ ! -d "$config_path" ]; then
    config_path="$STACK_DIR/cluster.json"
  fi

  if [ ! -d "$config_path" ]; then
    config_path="$PWD/cluster.json"
  fi

  domain="$(get_domain "$config_path")"
  zone_name="$(get_zone_name "$config_path")"

  assert_required_params "$domain" "$zone_name"

  load_balancer_name="$(get_load_balancer_name "$config_path")"
  load_balancer_dns="$(get_load_balancer_dns "$load_balancer_name")"
  load_balancer_target_zone="$(get_load_balancer_target_zone "$load_balancer_name")"
  route53_hosted_zone=$(get_route53_hosted_zone "$zone_name")

  if [ -z "$route53_hosted_zone" ] || [ "$route53_hosted_zone" == "null" ]; then
    echo "Could not find route53 hosted zone for: $domain"
    exit 1
  fi

  change_batch="$(generate_change_batch "$config_path" "$domain" "$load_balancer_dns" "$load_balancer_target_zone")"

  if [ "$dry_run" == "true" ]; then
    echo "$change_batch"
    exit 0
  fi

  tmpfile="$(mktemp)"
  echo "$change_batch" > "$tmpfile"

  aws route53 \
    change-resource-record-sets \
    --hosted-zone-id "$route53_hosted_zone" \
    --change-batch "file://$tmpfile" || fatal 'Unable to create route'
}

main "$@"
