#!/bin/bash

SCRIPT_NAME="stack-ensure-service"
SERVICE_SPEC_CACHE=""

source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

usage(){
  echo "USAGE: $SCRIPT_NAME <service-name>"
  echo 'Description: ensure a service is up-to-date'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help        print this help text'
  echo '  -v, --version     print the version'
  echo 'Environment:'
  echo '  DEBUG             print debug output'
}

assert_required_config() {
  require_config_value '.'
  require_config_value '.services[]'
}

assert_required_params() {
  local service_name="$1"
  if [ -z "$service_name" ]; then
    fatal 'Missing service-name as first arg'
  fi
}

get_env() {
  local service_name="$1"
  get_service_spec "$service_name" '.TaskTemplate.ContainerSpec.Env[]'
}

get_env_from_file() {
  local env_file="$1"
  if [ ! -f "$env_file" ]; then
    debug "no $env_file file"
    return 1
  fi
  for env_line in $(cat "$env_file"); do
    if [ -n "$env_line" ]; then
      echo "$env_line"
    fi
  done
}

get_env_add_options() {
  local service_name="$1"
  local env_file="$2"
  local opt_env_add
  local exists
  for env_line in $(get_env_from_file "$env_file"); do
    exists='false'
    for actual_env_line in $(get_env "$service_name"); do
      if [ "$actual_env_line" == "$env_line" ]; then
        exists='true'
        break;
      fi
    done
    if [ "$exists" == "false" ]; then
      debug "needs env: $env_line"
      opt_env_add="$opt_env_add --env-add $env_line"
    fi
  done
  echo "$opt_env_add"
}

get_env_rm_options() {
  local service_name="$1"
  local env_file="$2"
  local opt_env_rm=""
  local exists
  local actual_env_var=""
  local env_var
  for actual_env_line in $(get_env "$service_name"); do
    exists='false'
    actual_env_var="$(get_env_var "$actual_env_line")"
    if [ -z "$actual_env_var" ]; then
      continue;
    fi
    for env_line in $(get_env_from_file "$env_file"); do
      env_var="$(get_env_var "$env_line")"
      if [ "$env_var" == "$actual_env_var" ]; then
        exists='true'
        break;
      fi
    done
    if [ "$exists" == "false" ]; then
      debug "removing env: $actual_env_var"
      warn "Removing env $actual_env_var"
      opt_env_rm="$opt_env_rm --env-rm $actual_env_var"
    fi
  done
  echo "$opt_env_rm"
}

get_env_var() {
  local env_line="$1"
  echo "$env_line" | sed -e 's/\s*=.*//'
}

get_healthcheck_opt() {
  local service_name="$1"
  local opt_healthcheck
  local healthcheckDisable
  local healthcheckTimeout
  local healthcheckInterval
  local healthcheckCmd
  healthcheckDisable="$(get_service_val "$service_name" '.docker.healthcheck.disable')"
  healthcheckTimeout="$(get_service_val "$service_name" '.docker.healthcheck.timeout')"
  healthcheckInterval="$(get_service_val "$service_name" '.docker.healthcheck.interval')"
  healthcheckCmd="$(get_service_val "$service_name" '.docker.healthcheck.cmd')"
  healthcheckRetries="$(get_service_val "$service_name" '.docker.healthcheck.retries')"

  if [ "$healthcheckDisable" == "true" ]; then
    opt_healthcheck="--no-healthcheck"
  else
    if [ "$healthcheckCmd" != "" ]; then
      opt_healthcheck="$opt_healthcheck --health-cmd $healthcheckCmd"
    fi
    if [ "$healthcheckTimeout" != "" ]; then
      opt_healthcheck="$opt_healthcheck --health-timeout $healthcheckTimeout"
    fi
    if [ "$healthcheckInterval" != "" ]; then
      opt_healthcheck="$opt_healthcheck --health-interval $healthcheckInterval"
    fi
    if [ "$healthcheckRetries" != "" ]; then
      opt_healthcheck="$opt_healthcheck --health-retries $healthcheckRetries"
    fi
  fi
  echo "$opt_healthcheck"
}

get_service_spec_no_cache() {
  local service_name="$1"
  docker service inspect "$service_name" 2> /dev/null
}

get_service_spec() {
  local service_name="$1"
  local key="$2"
  if [ -z "$SERVICE_SPEC_CACHE" ]; then
    SERVICE_SPEC_CACHE="$(get_service_spec_no_cache "$service_name")" || return 1
  fi
  echo "$SERVICE_SPEC_CACHE" | jq --compact-output --raw-output ".[0].Spec${key}" 2> /dev/null
}

has_docker_socket() {
  local service_name="$1"
  local mounts
  local mountType
  local mountSource
  local mountTarget
  mounts=$(get_service_spec "$service_name" '.TaskTemplate.ContainerSpec.Mounts[]')
  local hasDockerSocket='false'
  local dockerSock='/var/run/docker.sock'
  for mount in $mounts; do
    debug 'mount' $mount
    mountType="$(echo "$mount" | jq --compact-output -r '.Type')"
    mountSource="$(echo "$mount" | jq --compact-output -r '.Source')"
    mountTarget="$(echo "$mount" | jq --compact-output -r '.Target')"
    if [ "$mountType" != "bind" ]; then
      continue
    fi
    if [ "$mountSource" != "$dockerSock" ]; then
      continue
    fi
    if [ "$mountTarget" != "$dockerSock" ]; then
      continue
    fi
    hasDockerSocket='true'
    break;
  done
  debug "has docker socket $hasDockerSocket"
  echo "$hasDockerSocket"
}

has_role() {
  local service_name="$1"
  local role="$2"
  local constraints
  constraints=$(get_service_spec "$service_name" '.TaskTemplate.Placement.Constraints[]')
  local hasRole='false'
  for constraint in $constraints; do
    debug "constraint '$constraint'"
    if [[ "$constraint" == *'node.role'* ]]; then
      debug 'constraint exists'
      hasRole='true'
      break;
    fi
  done
  debug "has role $hasRole"
  echo "$hasRole"
}

has_same_docker_image() {
  local service_name="$1"
  local expected_image="$2"
  local image
  image="$(get_service_spec "$service_name" '.TaskTemplate.ContainerSpec.Image')"
  if [ "$image" == "$expected_image" ]; then
    echo 'true'
  else
    echo 'false'
  fi
}

has_same_replicas() {
  local service_name="$1"
  local expected_count="$2"
  local count
  count="$(get_service_spec "$service_name" '.Mode.Replicated.Replicas')"
  if [ "$count" == "$expected_count" ]; then
    echo 'true'
  else
    echo 'false'
  fi
}

ensure_network() {
  local service_name="$1"
  docker network inspect "$service_name" &> /dev/null
  if [ "$?" != "0" ]; then
    debug "creating network $service_name"
    run_cmd docker network create --driver overlay "$service_name"  --attachable --subnet 10.10.9.0/24
    # sleepy time for docker
    sleep 10
  fi
}

ensure_service() {
  local service_name="$1"
  local opt_beekeeper
  local opt_docker_sock
  local opt_role
  local opt_publish
  local opt_traefik
  local opt_run
  local opt_env_add
  local opt_env_rm
  local opt_env
  local opt_with_registry_auth
  local opt_mode
  local opt_replicas
  local opt_logentries
  local opt_image
  local opt_healthcheck
  local service_name
  local count
  local docker_repo
  local network
  local mode
  local image
  local role
  local dockerSock
  local publish
  local traefikHost
  local traefikPathPrefix
  local runOptions
  local withRegistryAuth
  local logentries
  local envFile
  local beekeeper
  service_name="$(get_service_val "$service_name" '.name')"
  beekeeper="$(get_service_val "$service_name" '.beekeeper.update')"
  count="$(get_service_val "$service_name" '.count')"
  docker_repo="$(get_service_val "$service_name" '.docker.repo')"
  network="$(get_service_val "$service_name" '.docker.network')"
  mode="$(get_service_val "$service_name" '.docker.mode')"
  image="$(get_service_val "$service_name" '.docker.image')"
  role="$(get_service_val "$service_name" '.docker.role')"
  dockerSock="$(get_service_val "$service_name" '.docker.sock')"
  publish=( $(get_service_array_raw "$service_name" '.docker.publish[]') )
  traefikHost="$(get_service_val "$service_name" '.traefik.host')"
  traefikPathPrefix="$(get_service_val "$service_name" '.traefik.pathPrefix')"
  runOptions=( $(get_service_array_raw "$service_name" '.docker.runOptions[]') )
  withRegistryAuth="$(get_service_val "$service_name" '.docker.withRegistryAuth')"
  logentries="$(get_service_val "$service_name" '.docker.logentries')"
  envFile="$(get_service_val "$service_name" '.envFile')"
  local labelFlag='--label'
  local mountFlag='--mount'
  local publishFlag='--publish'
  local constraintFlag='--constraint'
  local isUpdate='false'
  if [ "$(get_service_spec "$service_name")" != "null" ] && [ "$(get_service_spec "$service_name")" != "" ]; then
    isUpdate='true'
    labelFlag='--label-add'
    mountFlag='--mount-add'
    publishFlag='--publish-add'
    constraintFlag='--constraint-add'
  fi
  if [ "$envFile" == "" ]; then
    envFile="$STACK_ENV_DIR/$service_name.env"
  fi
  if [ "$network" == "" ]; then
    network="traefik"
  fi
  if [ "$mode" == "" ]; then
    mode="replicated"
  fi
  if [ "$beekeeper" == "" ] || [ "$beekeeper" == "" ]; then
    beekeeper="false"
  fi
  if [ "$mode" == "replicated" ]; then
    if [ "$(has_same_replicas "$service_name" "$count")" == 'false' ]; then
      opt_replicas="--replicas $count"
    fi
  fi
  opt_mode="--mode $mode"
  if [ "$image" == "" ]; then
    if [ "$docker_repo" == "" ]; then
      image="$(swarm-get-latest-docker-url "octoblu/$service_name")"
    else
      image="$(swarm-get-latest-docker-url "$docker_repo")"
    fi
  fi
  if [ "$beekeeper" == "" ]; then
    beekeeper="true"
  fi
  if [ "$beekeeper" == "true" ]; then
    opt_beekeeper="$labelFlag octoblu.beekeeper.update=true"
  fi
  if [ "$beekeeper" == "false" ]; then
    opt_beekeeper="$labelFlag octoblu.beekeeper.update=false"
  fi
  if [ "$withRegistryAuth" == "true" ]; then
    opt_with_registry_auth="--with-registry-auth"
  fi
  if [ "$dockerSock" == "true" ]; then
    if [ "$(has_docker_socket "$service_name")" != 'true' ]; then
      opt_docker_sock="$mountFlag type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
    fi
  fi
  if [ "$role" != "" ]; then
    if [ "$(has_role "$service_name" "$role")" != 'true' ]; then
      opt_role="$constraintFlag node.role==$role"
    fi
  fi
  if [ "$traefikHost" != "" ]; then
    local frontendRule="Host:$traefikHost"
    if [ "$traefikPathPrefix" != "" ]; then
      frontendRule="${frontendRule};PathPrefix:${traefikPathPrefix}"
    fi
    opt_traefik="$labelFlag traefik.frontend.rule=${frontendRule} $labelFlag traefik.port=80 $labelFlag traefik.docker.network=traefik"
  fi
  if [ "$logentries" == "true" ]; then
    opt_logentries="--log-driver logentries --log-opt logentries-token=$OCTOSWARM_LOGENTRIES_TOKEN"
  else
    opt_logentries="--log-driver none"
  fi

  opt_healthcheck="$(get_healthcheck_opt "$service_name")"

  for port in "${publish[@]}"; do
    opt_publish="$opt_publish $publishFlag $port"
  done

  for option in "${runOptions[@]}"; do
    opt_run="$opt_run $option"
  done

  debug "publish $opt_publish run $opt_run"

  ensure_network "$network"

  run_cmd docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD" > /dev/null
  if [ "$isUpdate" == "true" ]; then
    debug 'updating service'
    if [ "$(has_same_docker_image "$service_name" "$image")" != 'true' ]; then
      opt_image="--image $image"
    fi
    opt_env_add="$(get_env_add_options "$service_name" "$envFile")"
    opt_env_rm="$(get_env_rm_options "$service_name" "$envFile")"
    run_cmd docker service update \
      $opt_docker_sock \
      $opt_role \
      $opt_replicas \
      $opt_traefik \
      $opt_beekeeper \
      $opt_with_registry_auth \
      $opt_image \
      $opt_env_add \
      $opt_env_rm \
      $opt_logentries \
      $opt_healthcheck \
      "$service_name"
  else
    debug 'creating service'
    if [ -f "$envFile" ]; then
      opt_env="--env-file $envFile"
    fi
    run_cmd docker service create \
      --name "$service_name" \
      --network "$network" \
      $opt_mode \
      $opt_replicas \
      $opt_publish \
      $opt_docker_sock \
      $opt_role \
      $opt_traefik \
      $opt_beekeeper \
      $opt_with_registry_auth \
      $opt_logentries \
      $opt_healthcheck \
      $opt_env \
      "$image" \
        $opt_run
  fi
  # sleepy time for docker
  sleep 10
}

main() {
  local service_name
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"

    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$service_name" ]; then
          service_name="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_config
  assert_required_params "$service_name"

  is_stack_empty || fatal 'Not initialized, run `create-cluster`'

  local exit_code
  local service
  service="$(get_service_by_name "$service_name")"
  if [ "$service" == "" ]; then
    fatal "Unable to find $service_name"
  fi
  if [ "$service_name" != "" ]; then
    ensure_service "$service_name"
    exit_code=$?
    SERVICE_SPEC_CACHE=""
    exit $exit_code
  fi
}

main "$@"
