#!/bin/bash

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

source "$(script_directory)/utils" || fatal 'unable to load utils'

debug() {
  debug_core "stack-create-worker" "$@"
}

assert_required_params(){
  local ip_address="$1"

  if [ -n "$ip_address" ]; then
    return 0
  fi

  usage

  if [ -z "$ip_address" ]; then
    echo "ip_address is missing"
  fi

  exit 1
}

usage(){
  echo 'USAGE: stack-create-worker'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help               print this help text'
  echo '  -t, --ec2-instance-type  ec2 instance type to spin up'
  echo '                           (default: t2.medium)'
  echo '  -v, --version            print the version'
  echo 'Environment:'
  echo '  DEBUG                    print debug output'
}

version(){
  local directory="$(script_directory)/.."

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown"
  fi
}

main() {
  local ec2_instance_type="t2.medium"

  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -t | --ec2-instance-type)
        ec2_instance_type="$value"
        shift
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        ;;
    esac
    shift
  done

  local ip_address="$(get_manager_private_ip)"
  assert_required_params "$ip_address"

  local machine_id="$(swarm-generate-machine-id worker)"
  local script_dir="$(script_directory)"

  "$script_dir/stack-create-machine" \
    --ec2-instance-type "$ec2_instance_type" "$machine_id" || fatal 'unable to create machine'

  swarm-join-worker --ip-address "$ip_address" --machine-id "$machine_id" || fatal 'unable to join-worker'
}

main "$@"
