#!/bin/bash

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

source "$(script_directory)/utils" || fatal 'unable to load utils'

debug() {
  debug_core "stack-destroy-cluster" "$@"
}

usage(){
  echo 'USAGE: stack destroy-cluster <path/to/stack>'
  echo 'Description: Destroy a cluster (more informational than destructive)'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help               print this help text'
  echo '  -v, --version            print the version'
  echo 'Environment:'
  echo '  DEBUG                    print debug output'
}

version(){
  local directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown"
  fi
}

assert_required_params(){
  local stack_path="$1"

  if [ -n "$stack_path" -a -d "$stack_path"  ]; then
    return 0
  fi

  usage

  if [ -z "$stack_path" ]; then
    echo "stack_path argument is missing"
  fi

  if [ ! -d "$stack_path" ]; then
    echo "$stack_path is not a directory"
  fi

  exit 1
}

remove_machine_config_files() {
  local stack_path="$1"
  local machine_files="${stack_path}/machine"
  if [ -d "${machine_files}" ]; then
    debug "removing ${machine_files}" 
    rm -rf "${machine_files}"
  fi
}

remove_machine_template_config_files() {
  local stack_path="$1"
  local machine_templates="${stack_path}/machine-template"
  if [ -d "${machine_templates}" ]; then
    debug "removing ${machine_templates}" 
    rm -rf "${machine_templates}"
  fi
}

main() {
  local stack_path
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"

    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$stack_path" ]; then
          stack_path="$param"
        fi
        ;;
    esac
    shift
  done

  if [ ! -d "$stack_path" ]; then
    stack_path="$STACK_ENV_DIR"
  fi

  if [ ! -d "$stack_path" ]; then
    stack_path="$PWD"
  fi

  assert_required_params "$stack_path"

  remove_machine_config_files "$stack_path"
  remove_machine_template_config_files "$stack_path"
  echo "The machine files and templates have been removed from this stack."
  echo "The old servers, load balancers, DNS records have not been touched, terminated, or removed."
  echo "Now just close octoswarm, and run 'stack ensure-cluster' inside of the folder with the cluster.json."
  echo "Once the new cluster is up and running, log into aws console and remove the old servers from the load balancers."
  echo "Once you confirm that the new cluster has successfully replaced the old cluster, terminate the old servers."
}

main "$@"
