#!/bin/bash

SCRIPT_NAME="stack-remove-machine"

# shellcheck disable=SC1091
source "/usr/src/app/stack/utils" || fatal 'unable to load utils'

assert_required_params() {
  local machine_id="$1"

  if [ -z "$machine_id" ]; then
    fatal "Missing machine-id as first argument"
  fi
}

usage(){
  echo "USAGE: $SCRIPT_NAME <machine-id>"
  echo ''
  echo 'Arguments:'
  echo '  -h, --help                       print this help text'
  echo '  -v, --version                    print the version'
  echo 'Environment:'
  echo '  AWS_ACCESS_KEY_ID      AWS Access ID'
  echo '  AWS_SECRET_ACCESS_KEY  AWS Secret Key'
  echo '  AWS_DEFAULT_REGION     AWS Default Region'
  echo '  DEBUG                  print debug output'
}

demote_machine() {
  local machine_id="$1"
  debug "demoting machine $machine_id"
  run_cmd docker node demote "$machine_id" > /dev/null
}

drain_machine() {
  local machine_id="$1"
  run_cmd docker node update --availability drain "$machine_id" > /dev/null
}

remove_docker_machine() {
  local machine_id="$1"
  debug "removing docker-machine $machine_id"
  run_cmd docker-machine rm --force "$machine_id" > /dev/null
}

remove_config() {
  local machine_id="$1"
  local config_folder="$MACHINE_STORAGE_PATH/machines/$machine_id"
  if [ -d "$config_folder" ]; then
    debug "removing $config_folder"
    rm -rf "$config_folder"
    return 0
  fi
  debug "config folder didn't exist $config_folder"
}

double_check() {
  local machine_id="$1"
  local good_to_go=''
  read -s -p "press 'y' to permanently delete this machine $machine_id"$'\n' -n 1 good_to_go
  if [[ "$good_to_go" == 'y' ]]; then
    return 0
  fi
  return 1
}

main() {
  local machine_id
  while [ "$1" != "" ]; do
    local param="$1"
    local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        if [ -z "$machine_id" ]; then
          machine_id="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$machine_id"

  double_check "$machine_id" || fatal 'Exiting...'
  demote_machine "$machine_id"
  drain_machine "$machine_id"
  remove_docker_machine "$machine_id"
  remove_config "$machine_id"
}

main "$@"
