#!/bin/bash

set_ulimit() {
  sudo sysctl -w kern.ipc.somaxconn=4096
  sudo sysctl -w kern.maxfiles=12288
  sudo sysctl -w kern.maxfilesperproc=10240
  ulimit -n 10240
}

say_yes() {
  local response
  if [ "$OVERRIDE_SAY_YES_OVERRIDE" == 'true' ]; then
    echo "You've choosen to not just always say yes. So we are not just gonna do it."
    read -s -p "press 'y' if you want to continue."$'\n' -n 1 response
    if [[ "$response" == 'y' ]]; then
      echo 'Good choice...'
      return 0
    fi
    echo 'Fine. Skipping...'
    return 1
  fi

  return 0
}

debug_core() {
  local debug_key="$1"; shift
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  if [ -z "$DEBUG" ]; then
    return 0
  fi
  echo "$debug_key" | grep "$DEBUG"
  local is_valid_debug="$?"
  if [ "$debug_key" == '*' -a "$is_valid_debug" != "0" ]; then
    return 0
  fi
  local message="$@"
  (>&2 echo -e "[${cyan}${debug_key}${no_color}]: $message")
}

fatal() {
  local message="$1"
  (>&2 echo "Error: $message")
  exit 1
}

get_machines() {
  docker-machine ls | grep -v ACTIVE
}

get_machine_names() {
  get_machines | awk '{print $1}'
}

get_nodes_by_role_unverified() {
  local role="$1"
  docker node ls --filter "role = $role" | grep -v HOSTNAME | sed 's/\*//' | awk '{print $2}'
}

get_nodes_by_role() {
  local role="$1"
  if [ -z "$STACK_DIR" ]; then
    debug 'cannot get nodes because it does not have STACK_DIR set'
    return 0
  fi
  for node_name in $(get_nodes_by_role_unverified "$role"); do
    verify_node_name "$node_name"
  done
}

verify_node_name() {
  local node_name="$1"
  if [ "$node_name" == "null" ]; then
    fatal "Unable to find a matching machine. Try and octoswarm in again."
  elif [ "$node_name" == "moby" ]; then
    fatal "Found a matching machine, but it is likely your local machine (moby). Try and octoswarm in again."
  else
    echo "$node_name"
  fi
}

get_managers() {
  get_nodes_by_role 'manager'
}

get_manager_ids() {
  get_managers
}

get_managers_count() {
  get_managers | wc -l | xargs
}

get_manager_id_unverified() {
  docker node ls --filter "role = manager" | grep -v HOSTNAME | grep '*' | sed 's/\*//' | awk '{print $2}'
}

get_manager_id() {
  if [ -z "$STACK_DIR" ]; then
    debug 'cannot get manager id because it does not have STACK_DIR set' 
    return 0
  fi
  local manager_id="$(get_manager_id_unverified)"
  verify_node_name "$manager_id"
}

get_manager_public_ip() {
  docker-machine ip "$(get_manager_id)"
}

get_manager_private_ip() {
  local public_ip="$(get_manager_public_ip)"
  aws ec2 describe-instances --filters "Name=ip-address,Values=$public_ip" | jq --raw-output  '.Reservations[].Instances[].PrivateIpAddress'
}

get_workers() {
  get_nodes_by_role 'worker'
}

get_workers_count() {
  get_workers | wc -l | xargs
}

service_exists() {
  local name="$1"
  for service_name in $(docker service ls | grep -v NAME | awk '{print $2}'); do
    if [ "$service_name" == "$name" ]; then
      return 0
    fi
  done
  return 1
}

elb_exists() {
  local elb_name="$1"
  aws elb describe-load-balancers --load-balancer-name "$elb_name" &> /dev/null || return 1
  return 0
}
