#!/bin/bash

usage(){
  echo 'USAGE:'
  echo "  Don't"
  echo ''
  echo 'DEPRECATED:'
  echo '  Use the tool octodns on the project'
  echo '  https://github.com/octoblu/octoswarm-dns'
  echo '  instead. octodns is available in homebrew'
  echo '  from the octoblu/tools tap.'
  echo ''
  echo 'Arguments:'
  echo '  -h, --help        print this help text'
  echo '  -v, --version     print the version'
  echo 'Environment:'
  echo '  DEBUG             print debug output'
}

main() {
  usage 1>&2 \
  && exit 1
}
main "$@"
